### ISSUE TITLE
Regarding "byggis run"

### ISSUE THREAD

**Issue by Kallzor** [Epos95/byggis#1]
Using the commando "byggis run" in map that got created by byggis it doesn't test the cases. Where are you suppose to use it? Maybe update readme to make this more clear :)

Thanks a lot

**Comment by Kallzor** [comment]
It seems like the problem is that i'm using Ubuntu and uses python3 when starting py files in the terminal byggis expects just "python" to work.

**Comment by Epos95** [comment]
Fixed with latest commit!
